{% set version = "6.7.2.42" %}

package:
  name: casatasks
  version: {{ version }}

source:
  fn: casa-{{ version }}.tar.gz
  url: https://open-bitbucket.nrao.edu/rest/api/latest/projects/CASA/repos/casa6/archive?at=refs%2Ftags%2F{{ version }}&format=tgz
  sha256: 5bcdfc745878fe1bb2ba57c6f6ecc587fb5a6da4371faeaa8b396560778590dc
  patches:
    - versioning.patch

build:
  number: 0
  noarch: python

requirements:
  build:
    - openjdk
  host:
    - casatools {{ version }}
    - certifi
    - matplotlib-base
    - pip
    - pyerfa
    - python {{ python_min }}
    - scipy
    - setuptools
  run:
    - casatools {{ version }}
    - certifi
    - matplotlib-base
    - pyerfa
    - python >={{ python_min }}
    - scipy
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - casatasks
    # A grab-bag of some of the task modules ...
    - casatasks.asdmsummary
    - casatasks.deconvolve
    - casatasks.flagdata
    - casatasks.hanningsmooth
    - casatasks.impbcor
    - casatasks.importvla
    - casatasks.plotweather
    - casatasks.rerefant
    - casatasks.sdintimaging
    - casatasks.smoothcal
    - casatasks.vishead

about:
  home: http://casa.nrao.edu/
  license: LGPL-2.1-or-later
  license_file: casatasks/src/LICENSE.txt
  summary: "Task implementations for CASA, the radio astronomical data processing package"

extra:
  recipe-maintainers:
    - pkgw
